// Initialize Characters

// empty position; placeholder character.
global.characters[0] = ds_map_create();
ds_map_add(global.characters[0], "type", "empty");
ds_map_add(global.characters[0], "displayName", "If you see this something went wrong")
ds_map_add(global.characters[0], "sprite", -1);
var attacks;
attacks[0] = ds_map_create();
ds_map_add(attacks[0], "id", 0);
ds_map_add(attacks[0], "sprite", -1);
ds_map_add(attacks[0], "displayName", "Placeholder attack");
ds_map_add(attacks[0], "Desc", "placeholder description");
ds_map_add(attacks[0], "charposition", [0, 0, 0, 0]);
ds_map_add(attacks[0], "targetposition", [0, 0, 0, 0]);
attacks[1] = ds_map_create();
ds_map_add(attacks[1], "id", 1);
ds_map_add(attacks[1], "sprite", -1);
ds_map_add(attacks[1], "displayName", "Placeholder attack");
attacks[2] = ds_map_create();
ds_map_add(attacks[2], "id", 2);
ds_map_add(attacks[2], "sprite", -1);
ds_map_add(attacks[2], "displayName", "Placeholder attack");
attacks[3] = ds_map_create();
ds_map_add(attacks[3], "id", 3);
ds_map_add(attacks[3], "sprite", -1);
ds_map_add(attacks[3], "displayName", "Placeholder attack");
ds_map_add(global.characters[0], "attacks", attacks);

// god gamer
global.characters[1] = ds_map_create();
ds_map_add(global.characters[1], "type", "godGamer");
ds_map_add(global.characters[1], "displayName", "God Gamer");
ds_map_add(global.characters[1], "sprite", sGodGamer);
var attacks;
attacks[0] = ds_map_create();
ds_map_add(attacks[0], "id", 0);
ds_map_add(attacks[0], "sprite", -1);
ds_map_add(attacks[0], "displayName", "Ban Hammer");
ds_map_add(attacks[0], "Desc", "Attack an enemy with the power of chat moderation.");
ds_map_add(attacks[0], "charposition", [0, 0, 1, 1]);
ds_map_add(attacks[0], "targetposition", [1, 1, 0, 0]);
attacks[1] = ds_map_create();
ds_map_add(attacks[1], "id", 1);
ds_map_add(attacks[1], "sprite", -1);
ds_map_add(attacks[1], "displayName", "Suck my Dick");
ds_map_add(attacks[1], "Desc", "Attack an distant target with chance to stun.");
ds_map_add(attacks[1], "charposition", [1, 1, 1, 1]);
ds_map_add(attacks[1], "targetposition", [0, 1, 1, 1]);
attacks[2] = ds_map_create();
ds_map_add(attacks[2], "id", 2);
ds_map_add(attacks[2], "sprite", -1);
ds_map_add(attacks[2], "displayName", "ShaShaa");
ds_map_add(attacks[2], "Desc", "Attack an enemy; gain riposte.");
ds_map_add(attacks[2], "charposition", [0, 0, 1, 1]);
ds_map_add(attacks[2], "targetposition", [1, 1, 0, 0]);
attacks[3] = ds_map_create();
ds_map_add(attacks[3], "id", 3);
ds_map_add(attacks[3], "sprite", -1);
ds_map_add(attacks[3], "displayName", "BlapBlapp");
ds_map_add(attacks[3], "Desc", "Attack 2 random targets with a gat.");
ds_map_add(attacks[3], "charposition", [1, 1, 1, 0]);
ds_map_add(attacks[3], "targetposition", [0, 1, 1, 1]);
attacks[4] = ds_map_create();
ds_map_add(attacks[4], "id", 4);
ds_map_add(attacks[4], "sprite", -1);
ds_map_add(attacks[4], "displayName", "Variety Stream");
ds_map_add(attacks[4], "Desc", "Attack all enemies, Random debuff for all enemies.");
ds_map_add(attacks[4], "charposition", [0, 1, 1, 0]);
ds_map_add(attacks[4], "targetposition", [1, 1, 1, 1]);
ds_map_add(global.characters[1], "attacks", attacks);

// Gaybriel
global.characters[2] = ds_map_create();
ds_map_add(global.characters[2], "type", "Party Member");
ds_map_add(global.characters[2], "displayName", "Gaybriel");
ds_map_add(global.characters[2], "sprite", sGaybriel);
var attacks;
attacks[0] = ds_map_create();
ds_map_add(attacks[0], "id", 0);
ds_map_add(attacks[0], "sprite", -1);
ds_map_add(attacks[0], "displayName", "RP spew");
ds_map_add(attacks[0], "Desc", "Targets 2 enemies with useless rant, lowers accuracy with chance to sleep");
ds_map_add(attacks[0], "charposition", [1, 1, 1, 0]);
ds_map_add(attacks[0], "targetposition", [1, 1, 1, 0]);
attacks[1] = ds_map_create();
ds_map_add(attacks[1], "id", 1);
ds_map_add(attacks[1], "sprite", -1);
ds_map_add(attacks[1], "displayName", "Confusing backstory");
ds_map_add(attacks[1], "Desc", "Make no sense, cause confusion to target enemy.");
ds_map_add(attacks[1], "charposition", [1, 1, 0, 0]);
ds_map_add(attacks[1], "targetposition", [1, 1, 1, 1]);
attacks[2] = ds_map_create();
ds_map_add(attacks[2], "id", 2);
ds_map_add(attacks[2], "sprite", -1);
ds_map_add(attacks[2], "displayName", "Self Destruction");
ds_map_add(attacks[2], "Desc", "Gaybriels ulimate sacrifice, deals alot of damage at the cost of Gaybriel");
ds_map_add(attacks[2], "charposition", [0, 1, 1, 0]);
ds_map_add(attacks[2], "targetposition", [1, 1, 1, 1]);
attacks[3] = ds_map_create();
ds_map_add(attacks[3], "id", 3);
ds_map_add(attacks[3], "sprite", -1);
ds_map_add(attacks[3], "displayName", "LARP death blossom");
ds_map_add(attacks[3], "Desc", "Attacks all enemies with rubbet bullets, does minor damage.");
ds_map_add(attacks[3], "charposition", [0, 0, 1, 1]);
ds_map_add(attacks[3], "targetposition", [1, 1, 1, 1]);
attacks[4] = ds_map_create();
ds_map_add(attacks[4], "id", 4);
ds_map_add(attacks[4], "sprite", -1);
ds_map_add(attacks[4], "displayName", "Life Steal");
ds_map_add(attacks[4], "Desc", "Target enemy, deals damage and heals Gaybriel.");
ds_map_add(attacks[4], "charposition", [0, 1, 1, 0]);
ds_map_add(attacks[4], "targetposition", [1, 1, 0, 0]);
ds_map_add(global.characters[2], "attacks", attacks);

// Tesla Model S
global.characters[3] = ds_map_create();
ds_map_add(global.characters[3], "type", "Party Member");
ds_map_add(global.characters[3], "displayName", "Tesla Model S");
ds_map_add(global.characters[3], "sprite", stesla);
var attacks;
attacks[0] = ds_map_create();
ds_map_add(attacks[0], "id", 0);
ds_map_add(attacks[0], "sprite", -1);
ds_map_add(attacks[0], "displayName", "Hit and Run");
ds_map_add(attacks[0], "Desc", "Run down target enemy with chance to bleed.");
ds_map_add(attacks[0], "charposition", [0, 1, 1, 1]);
ds_map_add(attacks[0], "targetposition", [1, 1, 1, 0]);
attacks[1] = ds_map_create();
ds_map_add(attacks[1], "id", 1);
ds_map_add(attacks[1], "sprite", -1);
ds_map_add(attacks[1], "displayName", "Sentry Mode Protection");
ds_map_add(attacks[1], "Desc", "Defends ally target, increasing armor for the Tesla.");
ds_map_add(attacks[1], "charposition", [0, 0, 1, 1]);
ds_map_add(attacks[1], "targetAllyposition", [1, 1, 1, 1]);
attacks[2] = ds_map_create();
ds_map_add(attacks[2], "id", 2);
ds_map_add(attacks[2], "sprite", -1);
ds_map_add(attacks[2], "displayName", "Autopilot Assistance");
ds_map_add(attacks[2], "Desc", "Team evasion buff, insuring a safe drive in a Tesla");
ds_map_add(attacks[2], "charposition", [0, 1, 1, 1]);
ds_map_add(attacks[2], "targetAllyposition", [1, 1, 1, 1]);
attacks[3] = ds_map_create();
ds_map_add(attacks[3], "id", 3);
ds_map_add(attacks[3], "sprite", -1);
ds_map_add(attacks[3], "displayName", "Fully Retractable Sunroof");
ds_map_add(attacks[3], "Desc", "Increases style, which isn't a mechanic in our game, but also gives the parties accuracy.");
ds_map_add(attacks[3], "charposition", [0, 1, 0, 1]);
ds_map_add(attacks[3], "targetAllyposition", [1, 1, 1, 1]);
attacks[4] = ds_map_create();
ds_map_add(attacks[4], "id", 4);
ds_map_add(attacks[4], "sprite", -1);
ds_map_add(attacks[4], "displayName", "Tesla Overdrive");
ds_map_add(attacks[4], "Desc", "Hidden deployable laser to melt enemies.");
ds_map_add(attacks[4], "charposition", [0, 0, 1, 1]);
ds_map_add(attacks[4], "targetposition", [1, 1, 1, 0]);
ds_map_add(global.characters[3], "attacks", attacks);

// Suzuki Teriyaki
global.characters[4] = ds_map_create();
ds_map_add(global.characters[4], "type", "Party Member");
ds_map_add(global.characters[4], "displayName", "Suzuki Teryiaki");
ds_map_add(global.characters[4], "sprite", sSuzuki);
var attacks;
attacks[0] = ds_map_create();
ds_map_add(attacks[0], "id", 0);
ds_map_add(attacks[0], "sprite", -1);
ds_map_add(attacks[0], "displayName", "Sword Slash");
ds_map_add(attacks[0], "Desc", "Attack an enemy, moves forward one space.");
ds_map_add(attacks[0], "charposition", [0, 0, 1, 1]);
ds_map_add(attacks[0], "targetposition", [1, 1, 0, 0]);
attacks[1] = ds_map_create();
ds_map_add(attacks[1], "id", 1);
ds_map_add(attacks[1], "sprite", -1);
ds_map_add(attacks[1], "displayName", "Black Rock Shooter");
ds_map_add(attacks[1], "Desc", "Shoots arm cannon, falls back one space.");
ds_map_add(attacks[1], "charposition", [0, 1, 1, 1]);
ds_map_add(attacks[1], "targetposition", [0, 1, 1, 1]);
attacks[2] = ds_map_create();
ds_map_add(attacks[2], "id", 2);
ds_map_add(attacks[2], "sprite", -1);
ds_map_add(attacks[2], "displayName", "Full Body Pillow Slam");
ds_map_add(attacks[2], "Desc", "Attack an enemy, with chance to stun.");
ds_map_add(attacks[2], "charposition", [0, 0, 1, 1]);
ds_map_add(attacks[2], "targetposition", [1, 1, 1, 0]);
attacks[3] = ds_map_create();
ds_map_add(attacks[3], "id", 3);
ds_map_add(attacks[3], "sprite", -1);
ds_map_add(attacks[3], "displayName", "AYAYA");
ds_map_add(attacks[3], "Desc", "Lets out an AYAYA, enemies get DEF debuff.");
ds_map_add(attacks[3], "charposition", [1, 0, 1, 0]);
ds_map_add(attacks[3], "targetposition", [1, 1, 1, 1]);
attacks[4] = ds_map_create();
ds_map_add(attacks[4], "id", 3);
ds_map_add(attacks[4], "sprite", -1);
ds_map_add(attacks[4], "displayName", "Full on AYAYA");
ds_map_add(attacks[4], "Desc", "Attacks all enemies for huge damage.");
ds_map_add(attacks[4], "charposition", [0, 1, 0, 0]);
ds_map_add(attacks[4], "targetposition", [1, 1, 1, 1]);
ds_map_add(global.characters[4], "attacks", attacks);

// Purple Lady Face
global.characters[5] = ds_map_create();
ds_map_add(global.characters[5], "type", "Party Member");
ds_map_add(global.characters[5], "displayName", "Purple Lady Face");
ds_map_add(global.characters[5], "sprite", sPurple);
var attacks;
attacks[0] = ds_map_create();
ds_map_add(attacks[0], "id", 0);
ds_map_add(attacks[0], "sprite", -1);
ds_map_add(attacks[0], "displayName", "Smug Face");
ds_map_add(attacks[0], "Desc", "Attack an enemy, dodge self buff");
ds_map_add(attacks[0], "charposition", [0, 0, 1, 1]);
ds_map_add(attacks[0], "targetposition", [1, 1, 0, 0]);
attacks[1] = ds_map_create();
ds_map_add(attacks[1], "id", 1);
ds_map_add(attacks[1], "sprite", -1);
ds_map_add(attacks[1], "displayName", "Toxic Spam");
ds_map_add(attacks[1], "Desc", "Attack two rear enemies, chance for bleed damage.");
ds_map_add(attacks[1], "charposition", [0, 1, 1, 1]);
ds_map_add(attacks[1], "targetposition", [0, 0, 1, 1]);
attacks[2] = ds_map_create();
ds_map_add(attacks[2], "id", 2);
ds_map_add(attacks[2], "sprite", -1);
ds_map_add(attacks[2], "displayName", "Snipe");
ds_map_add(attacks[2], "Desc", "Attack an enemy, chance to increase accuracy.");
ds_map_add(attacks[2], "charposition", [1, 1, 1, 0]);
ds_map_add(attacks[2], "targetposition", [0, 0, 1, 1]);
attacks[3] = ds_map_create();
ds_map_add(attacks[3], "id", 3);
ds_map_add(attacks[3], "sprite", -1);
ds_map_add(attacks[3], "displayName", "Rushdown");
ds_map_add(attacks[3], "Desc", "Attack frontline enemy.");
ds_map_add(attacks[3], "charposition", [0, 0, 1, 1]);
ds_map_add(attacks[3], "targetposition", [1, 0, 0, 0]);
attacks[4] = ds_map_create();
ds_map_add(attacks[4], "id", 3);
ds_map_add(attacks[4], "sprite", -1);
ds_map_add(attacks[4], "displayName", "Now I'm mad moon2A");
ds_map_add(attacks[4], "Desc", "All enemies get accuracy debuff, with chance for bleed.");
ds_map_add(attacks[4], "charposition", [0, 1, 1, 0]);
ds_map_add(attacks[4], "targetposition", [1, 1, 1, 1]);
ds_map_add(global.characters[5], "attacks", attacks);

// 
global.characters[5] = ds_map_create();
ds_map_add(global.characters[5], "type", "Party Member");
ds_map_add(global.characters[5], "displayName", "Purple Lady Face");
ds_map_add(global.characters[5], "sprite", sPurple);
var attacks;
attacks[0] = ds_map_create();
ds_map_add(attacks[0], "id", 0);
ds_map_add(attacks[0], "sprite", -1);
ds_map_add(attacks[0], "displayName", "Smug Face");
ds_map_add(attacks[0], "Desc", "Attack an enemy, dodge self buff");
ds_map_add(attacks[0], "charposition", [0, 0, 1, 1]);
ds_map_add(attacks[0], "targetposition", [1, 1, 0, 0]);
attacks[1] = ds_map_create();
ds_map_add(attacks[1], "id", 1);
ds_map_add(attacks[1], "sprite", -1);
ds_map_add(attacks[1], "displayName", "Toxic Spam");
ds_map_add(attacks[1], "Desc", "Attack two rear enemies, chance for bleed damage.");
ds_map_add(attacks[1], "charposition", [0, 1, 1, 1]);
ds_map_add(attacks[1], "targetposition", [0, 0, 1, 1]);
attacks[2] = ds_map_create();
ds_map_add(attacks[2], "id", 2);
ds_map_add(attacks[2], "sprite", -1);
ds_map_add(attacks[2], "displayName", "Snipe");
ds_map_add(attacks[2], "Desc", "Attack an enemy, chance to increase accuracy.");
ds_map_add(attacks[2], "charposition", [1, 1, 1, 0]);
ds_map_add(attacks[2], "targetposition", [0, 0, 1, 1]);
attacks[3] = ds_map_create();
ds_map_add(attacks[3], "id", 3);
ds_map_add(attacks[3], "sprite", -1);
ds_map_add(attacks[3], "displayName", "Rushdown");
ds_map_add(attacks[3], "Desc", "Attack frontline enemy.");
ds_map_add(attacks[3], "charposition", [0, 0, 1, 1]);
ds_map_add(attacks[3], "targetposition", [1, 0, 0, 0]);
attacks[4] = ds_map_create();
ds_map_add(attacks[4], "id", 3);
ds_map_add(attacks[4], "sprite", -1);
ds_map_add(attacks[4], "displayName", "Now I'm mad moon2A");
ds_map_add(attacks[4], "Desc", "All enemies get accuracy debuff, with chance for bleed.");
ds_map_add(attacks[4], "charposition", [0, 1, 1, 0]);
ds_map_add(attacks[4], "targetposition", [1, 1, 1, 1]);
ds_map_add(global.characters[5], "attacks", attacks);



global.order = [1, 2, 0, 2];
global.selected = -1
room_goto_next();
